### PR TITLE
Change git URL to public repo

### PR DESCRIPTION
**Pull request by frew**

### CODE REVIEW

**Comment by grundprinzip** [comment]
Hi, 

can you please send the patch to http://gerrit.cloudera.org:8080/#/q/project:kudu+status:open?

Thanks a lot!
Martin

**Comment by toddlipcon** [comment]
Actually I made the same change yesterday via gerrit, but looks like something has "stuck" our gerrit -> github mirroring: http://gerrit.cloudera.org:8080/#/c/1066/

**Comment by toddlipcon** [comment]
Oh, I see what happened. This pull request is for the gh-pages branch, but my commit yesterday fixed the doc sources in master:docs/. Need to re-build the docs and push gh-pages for it to hit the gh-pages site. I'll do that momentarily.

**Comment by toddlipcon** [comment]
http://gerrit.cloudera.org:8080/#/c/1079/ should fix this. Thanks, Fred!

**Pull request closed without merging**
