### PR TITLE
Fix broken url to "Better Bloom Filter" paper

### PR DESCRIPTION
**Pull request by andrelaszlo**
I noticed that this link was broken so I replaced it with a link to a copy provided by the other author

### CODE REVIEW

**Comment by danburkert** [comment]
Hi @andrelaszlo, we actually can't take PRs on this repo, could you push your patch to our gerrit instance?  We have instructions [here](https://kudu.apache.org/docs/contributing.html#_contributing_patches_using_gerrit).  Thanks!

**Comment by danburkert** [comment]
Just noticed this is a more-or-less automated PR, so I'm going to try and upstream it on your behalf.  Thanks again.

**Comment by andrelaszlo** [comment]
Thanks @danburkert, I appreciate it :)

**Comment by danburkert** [comment]
Merged upstream here: https://github.com/apache/kudu/commit/4347174d7e78f27a69c28ef1c8e551649d2173c5.  @toddlipcon  you can close this out.

**Comment by granthenke** [comment]
@andrelaszlo I am curious how you opened so many pull requests across so many repositories. Do you have some sort of find and replace script?

**Comment by andrelaszlo** [comment]
@granthenke GitHub's search, fork, PR and repo API's in combination with `git grep` and `sed`. All in a Bash script. I saw someone doing something similar with common typos so I wanted to see how hard it is. I hope I don't come across as too spammy - I actually felt this was at least a little bit useful since I came across the same dead link in so many repos when I was researching Bloom filter implementations. :)

**Comment by granthenke** [comment]
Thanks for the explanation @andrelaszlo! It definitely can come in handy for some widespread issues. Would you mind sharing a gist of the script?

**Comment by andrelaszlo** [comment]
@granthenke Sure [here it is](https://gist.github.com/andrelaszlo/2e96027b531f6b177e73bef7ab064fbf). Not very robust or pretty, but apparently it works :) First attempt was a Python script but I didn't like the GitHub clients.

**Comment by granthenke** [comment]
@andrelaszlo Cool. Thanks for sharing!

**Pull request closed without merging**
